export class Ratecard {
    name: String;
    type: String;
    baseFare: String;
    ratePerKM: String;
    ratePerMinute: String;
    inclusiveDistance: String;
    otherCharges: String;
    driverDA: String;
    driverDATimingsFrom: String;
    driverDATimingsFromAMPM: String;
    driverDATimingsTo: String;
    driverDATimingsToAMPM: String;
    airportPickup:String;
    airportDrop:String;
    roundTrip:String;
    ratePerExtraKM:String;
    ragePerWaitMinute:String;
    serviceTax:String;
    otherTaxes:String;
    inclusiveTime:String;
    hoursInPackage:String;
    extraKMCharge:String;
    extraHourCharge:String;
    applyTwoWay:String;
    from:String;
    to:String;
    fees:String;
    tollAndParking:String;
}